import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* check if we're in development environment and show debug screen size */}
      <body
        className={`${
          process.env.NODE_ENV === "development" ? "debug-screens" : ""
        } ${inter.className}`}
      >
        {children}
      </body>
    </html>
  );
}
